const mockEvents = [
  {
    id: "evt-1",
    title: "Product Standup",
    description: "Daily check-in with engineering and design.",
    start: "2024-05-14T09:00:00",
    end: "2024-05-14T09:30:00",
    attendeeCount: 7,
    userRole: "contributor",
    meetingType: "standup",
    emotionalIntensity: "routine",
    topicTags: ["delivery", "product"],
  },
  {
    id: "evt-2",
    title: "Customer Feedback Review",
    description: "Review escalation and decide on next steps.",
    start: "2024-05-14T10:00:00",
    end: "2024-05-14T11:00:00",
    attendeeCount: 4,
    userRole: "decision_maker",
    meetingType: "decision",
    emotionalIntensity: "feedback",
    topicTags: ["support", "retention"],
  },
  {
    id: "evt-3",
    title: "Design Review: Onboarding",
    description: "Finalize UX flows for onboarding.",
    start: "2024-05-14T11:15:00",
    end: "2024-05-14T12:00:00",
    attendeeCount: 5,
    userRole: "contributor",
    meetingType: "design_review",
    emotionalIntensity: "feedback",
    topicTags: ["onboarding", "ux"],
  },
  {
    id: "evt-4",
    title: "Partnership Sync",
    description: "External partner check-in and roadmap alignment.",
    start: "2024-05-14T13:00:00",
    end: "2024-05-14T14:00:00",
    attendeeCount: 9,
    userRole: "occasional_contributor",
    meetingType: "status",
    emotionalIntensity: "external",
    topicTags: ["partnerships", "roadmap"],
  },
  {
    id: "evt-5",
    title: "Brainstorm: AI Ops",
    description: "Explore new AI ops flows for support tooling.",
    start: "2024-05-14T15:00:00",
    end: "2024-05-14T16:30:00",
    attendeeCount: 6,
    userRole: "contributor",
    meetingType: "brainstorming",
    emotionalIntensity: "performance",
    topicTags: ["ai", "support"],
  },
  {
    id: "evt-6",
    title: "Conflict Resolution",
    description: "Address blockers between teams.",
    start: "2024-05-14T17:00:00",
    end: "2024-05-14T17:45:00",
    attendeeCount: 3,
    userRole: "decision_maker",
    meetingType: "conflict",
    emotionalIntensity: "conflict",
    topicTags: ["alignment", "roadmap"],
  },
];

module.exports = { mockEvents };
